---
title: "Simulation Result For Three-Level Intercept Model With Low Prevalence"
author: Shafayet Khan Shafee
date: last-modified
date-format: "DD MMMM YYYY"
format: html
embed-resources: true
---


```{r}
#| echo: false
#| message: false
#| warning: false

library(dplyr)
library(kableExtra)

final_res_int_low_prev <- readRDS(
  here::here("sim-results/rds/sim_res_three_lvl_int_low_prev.rds")
  )

mean_prevalence <- round(mean(final_res_int_low_prev$prevalence), 2)*100
```


---
subtitle: "The mean prevalence for this simulation is `r mean_prevalence` %"
---

<!-- --------------------------------------------------------------------------- -->
<!-- --------------------------------------------------------------------------- -->
<!-- --------------------------------------------------------------------------- -->

# Simulation Result Table for MOR of Second Level

```{r}
#| echo: false
sim_output_table <- final_res_int_low_prev %>%
  mutate(
    ratio1 = se_mor1_hat / sim_se_mor1_hat,
    ratio2 = se_mor2_hat / sim_se_mor2_hat
    ) %>%
  select(ea_number, hh_number, hh_size, beta0_hat, beta1_hat, beta2_hat,
         sigma_u_sq_hat, sigma_v_sq_hat,
         mor1_hat, relative_bias_1, se_mor1_hat,
         sim_se_mor1_hat, ratio1, coverage_1,
         mor2_hat, relative_bias_2, se_mor2_hat,
         sim_se_mor2_hat, ratio2, coverage_2,
         convergence = converged)
```


```{r}
#| echo: false
mor1_table <- sim_output_table %>% 
  select(ea_number, hh_number, hh_size, beta0_hat, beta1_hat, beta2_hat,
         sigma_u_sq_hat, sigma_v_sq_hat,
         mor1_hat, relative_bias_1, se_mor1_hat,
         sim_se_mor1_hat, ratio1, coverage_1,
         convergence)

mor2_table <- sim_output_table %>% 
  select(ea_number, hh_number, hh_size, beta0_hat, beta1_hat, beta2_hat,
         sigma_u_sq_hat, sigma_v_sq_hat,
         mor2_hat, relative_bias_2, se_mor2_hat,
         sim_se_mor2_hat, ratio2, coverage_2,
         convergence)
```


```{r}
#| echo: false
kableExtra::kbl(mor1_table, digits = 2) %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "responsive"))
```


# Simulation Result Table for MOR of Third Level


```{r}
#| echo: false
kableExtra::kbl(mor2_table, digits = 2) %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "responsive"))
```


# Simulation Result Table All Together

```{r}
#| echo: false
kableExtra::kbl(sim_output_table, digits = 2) %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "responsive"))

```
